### ISSUE TITLE
Missing attribute assertions

### ISSUE THREAD

**Issue by jkrems** [testiumjs/testium-driver-wd#12]
According to the docs [`browser.assertElementHasAttributes`](http://testiumjs.com/api/wd/#browserassertelementhasattributesselector-attributesobject) should be a thing but quite obviously there's no implementation for it. We should either implement it or remove it from the docs. Preferably the former.

**Comment by dbushong** [comment]
Fixed in https://github.com/testiumjs/testium-driver-wd/pull/17
